<?php

namespace Tests\Feature\Api\Auth;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * Class ProfileTest
 *
 * @package \Tests\Feature\Api\Auth
 */
class ProfileTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadUsersWithPermission();
    }

    /** @test */
    public function can_fetch_profile_data_for_authenticated_user()
    {

        $user =   $this->agentUser;
        $this->signIn($user->getModel());

        $this->json('GET', route('api.profile.get'))
            ->assertStatus(200)
            ->assertJson(['status' => 'success', 'data' => ['name' => $user->getName()]]);
    }


    /** @test */
    public function must_not_be_able_to_fetch_profile_for_none_authenticated_user()
    {

        $this->json('GET', route('api.profile.get'))
            ->assertStatus(401) ;
    }



}
